/**
 * Lets a re-import PATCH an already-existing, user-edited note instead of the
 * usual all-or-nothing choice (see NoteBuilder.GeneratedNote.regenerate):
 * NoteBuilder wraps every purely-derived block (day/time/scripture fields,
 * headings, the "Anschließend" hint, …) in an invisible marker pair —
 * `<span class="jw-marker" data-jw-start="id"></span> … <span class="jw-marker"
 * data-jw-end="id"></span>`, hidden via this plugin's own `styles.css` rule
 * (`.jw-marker { display: none; }`), so it never shows in Reading View OR
 * Live Preview, regardless of cursor position. mergeNoteContent() then takes
 * the EXISTING file's raw text and a FRESHLY rendered version of the same
 * note (e.g. after a parser bug was fixed) and replaces only the content
 * inside matching marker pairs, leaving every line outside them — including a
 * user's own typed speaker name, personal notes, or an edited YAML
 * frontmatter block — byte-for-byte untouched.
 *
 * Deliberately conservative: any structural mismatch (missing markers,
 * different marker ids/order/count, malformed nesting) makes it return
 * `null` rather than guess at a merge — the caller then falls back to
 * leaving the file alone entirely, exactly like today's plain re-import.
 * This is also why plugin-version notes older than this feature (no markers
 * at all) can never be merged: there's nothing to safely anchor the swap to.
 *
 * Versions up to and including 1.18.0 used Obsidian's own `%%jw:id%% …
 * %%/jw:id%%` comment syntax for these markers — turned out to always render
 * as dimmed, visible text in Live Preview (unlike Reading View, which drops
 * `%%…%%` entirely), independent of cursor position, since Obsidian has no
 * built-in "fully invisible" handling for that syntax specifically. The
 * legacy pattern is still recognized when READING an existing note (so
 * notes generated by 1.9.0–1.18.0 keep merging correctly — and get silently
 * upgraded to the new span markers the next time they're merged, since fresh
 * content always uses the new format), but nothing is ever WRITTEN in the
 * old format again.
 */

// The optional data-jw-kept="1" is how a block says "the user corrected this
// on purpose, leave it alone" — see markBlockKept() and the module doc's
// section on it. Written only by the plugin's own edit actions, never by
// NoteBuilder, so a freshly generated note never carries it.
const MARKER_START_RE = /^<span class="jw-marker" data-jw-start="([A-Za-z0-9_-]+)"( data-jw-kept="1")?><\/span>$/;
const MARKER_END_RE = /^<span class="jw-marker" data-jw-end="([A-Za-z0-9_-]+)"><\/span>$/;
// 1.9.0–1.18.0 marker format — read-only, see module doc comment above.
const LEGACY_MARKER_START_RE = /^%%jw:([A-Za-z0-9_-]+)%%$/;
const LEGACY_MARKER_END_RE = /^%%\/jw:([A-Za-z0-9_-]+)%%$/;

function matchStart(line: string): { id: string; kept: boolean } | null {
	const current = MARKER_START_RE.exec(line);
	if (current) return { id: current[1]!, kept: current[2] !== undefined };
	const legacy = LEGACY_MARKER_START_RE.exec(line);
	// The 1.9.0–1.18.0 format has nowhere to carry the flag, and never did.
	return legacy ? { id: legacy[1]!, kept: false } : null;
}

function matchEnd(line: string): string | null {
	return MARKER_END_RE.exec(line)?.[1] ?? LEGACY_MARKER_END_RE.exec(line)?.[1] ?? null;
}

interface MarkerBlock {
	id: string;
	startLine: number;
	endLine: number;
	/** The user corrected this block themselves; an update leaves it as it is. */
	kept: boolean;
}

/** Parses top-level (non-nested — markers never nest in NoteBuilder's own output) marker
 *  pairs out of `lines`, in document order. Returns null on any malformed/unbalanced marker.
 *  Recognizes both the current span-based markers and the legacy %%jw:id%% ones (see module doc). */
function findMarkerBlocks(lines: string[]): MarkerBlock[] | null {
	const blocks: MarkerBlock[] = [];
	let open: { id: string; startLine: number; kept: boolean } | null = null;

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i]!.trim();
		const start = matchStart(line);
		if (start !== null) {
			if (open) return null; // nested/unclosed marker — not a shape NoteBuilder produces
			open = { id: start.id, startLine: i, kept: start.kept };
			continue;
		}
		const endId = matchEnd(line);
		if (endId !== null) {
			if (!open || open.id !== endId) return null; // mismatched close
			blocks.push({ id: open.id, startLine: open.startLine, endLine: i, kept: open.kept });
			open = null;
		}
	}
	if (open) return null; // unclosed at end of file
	return blocks;
}

/** Splits a leading YAML frontmatter block (`---\n…\n---`) off `lines`, if present. */
function splitFrontmatter(lines: string[]): { frontmatterEndLine: number } | null {
	if (lines[0] !== '---') return null;
	for (let i = 1; i < lines.length; i++) {
		if (lines[i] === '---') return { frontmatterEndLine: i };
	}
	return null;
}

/**
 * Merges `fresh` (a newly rendered version of the same note) into `existing`
 * (the file's current on-disk content): the YAML frontmatter block (if both
 * have one — fully machine-generated, see NoteBuilder.frontmatterLines(), so
 * always safe to replace outright) and every matching marker region are
 * taken from `fresh`; everything else is kept from `existing` verbatim.
 * Returns null when the two don't line up structurally (see module doc).
 */
/**
 * Wraps whatever `render()` pushes onto `lines` in an invisible marker pair
 * (see module doc comment for the exact format and why) — used by
 * NoteBuilder/MwbNoteBuilder to mark every purely-derived block (day/time/
 * scripture fields, headings, the "Anschließend" hint, …) so
 * mergeNoteContent() can later patch just that block in an already-existing
 * note. A no-op (no marker added) when `render()` pushes nothing, so optional
 * fields that don't apply to a given item don't leave behind an empty marker
 * pair.
 */
/** True when `content` has no marker line at all (current span format OR the
 *  legacy %%jw:…%% one) — the only case where the legacy-field heuristic
 *  (util/legacyFieldPatch.ts) is safe to attempt as a fallback after
 *  mergeNoteContent() returns null. Any OTHER reason for a null result
 *  (corrupted/reordered/mismatched markers, frontmatter appearing or
 *  disappearing) must still be reported as needing a full re-import and left
 *  alone — sweeping a note with damaged markers into the marker-blind text
 *  heuristic could misinterpret content that's actually inside a broken
 *  marker region. */
export function hasNoMarkers(content: string): boolean {
	return !content.split('\n').some(line => {
		const trimmed = line.trim();
		return matchStart(trimmed) !== null || matchEnd(trimmed) !== null;
	});
}

/**
 * Marks the block containing `lineIndex` as the user's own, so later updates
 * leave it alone. The flag goes on that block's opening marker, which is
 * invisible in both Reading View and Live Preview like every other marker.
 *
 * This is what keeps a correction made through the plugin's own edit actions
 * from being undone by the next "update notes" run. Without it, changing a
 * derived field — a song number the congregation actually sang, a reference
 * the programme got wrong — would look as though it worked and quietly revert
 * later, which is worse than not offering the change at all.
 *
 * Returns the lines unchanged when `lineIndex` lies outside every block: text
 * the user typed themselves is never overwritten to begin with, so it needs
 * no flag.
 */
export function markBlockKept(lines: string[], lineIndex: number): string[] {
	const blocks = findMarkerBlocks(lines);
	if (!blocks) return lines;
	const block = blocks.find(b => lineIndex > b.startLine && lineIndex < b.endLine);
	if (!block || block.kept) return lines;
	const startLine = lines[block.startLine]!;
	// Only the current span format can carry the flag. A legacy %%jw:id%%
	// marker becomes a span on its next merge anyway, and flagging it here
	// would produce a line neither format recognises.
	if (!MARKER_START_RE.test(startLine.trim())) return lines;
	const updated = lines.slice();
	updated[block.startLine] = startLine.replace(
		/ data-jw-start="([A-Za-z0-9_-]+)"/,
		' data-jw-start="$1" data-jw-kept="1"',
	);
	return updated;
}

export function pushMarked(lines: string[], id: string, render: () => void): void {
	const start = lines.length;
	render();
	if (lines.length === start) return;
	lines.splice(start, 0, `<span class="jw-marker" data-jw-start="${id}"></span>`);
	lines.push(`<span class="jw-marker" data-jw-end="${id}"></span>`);
}

/** The two notes lined up for merging: frontmatter split off, bodies split
 *  into lines, and their marker blocks confirmed to correspond one to one. */
interface AlignedNotes {
	frontmatterPrefix: string[];
	existingFrontmatter: string[];
	existingBody: string[];
	freshBody: string[];
	existingBlocks: MarkerBlock[];
	freshBlocks: MarkerBlock[];
}

/** Every structural rule the merge insists on, in one place — so that
 *  diffNoteContent() reports a change exactly when mergeNoteContent() would
 *  make one, and refuses exactly when it would refuse. A preview computed by
 *  its own rules could drift from what actually gets written, which is the
 *  one thing a preview must never do. */
function alignNotes(existing: string, fresh: string): AlignedNotes | null {
	const existingLines = existing.split('\n');
	const freshLines = fresh.split('\n');

	const existingFm = splitFrontmatter(existingLines);
	const freshFm = splitFrontmatter(freshLines);
	if (Boolean(existingFm) !== Boolean(freshFm)) return null; // frontmatter appeared/disappeared — unexpected, bail

	const existingBodyStart = existingFm ? existingFm.frontmatterEndLine + 1 : 0;
	const freshBodyStart = freshFm ? freshFm.frontmatterEndLine + 1 : 0;

	const existingBody = existingLines.slice(existingBodyStart);
	const freshBody = freshLines.slice(freshBodyStart);

	const existingBlocks = findMarkerBlocks(existingBody);
	const freshBlocks = findMarkerBlocks(freshBody);
	if (!existingBlocks || !freshBlocks) return null;
	if (existingBlocks.length === 0 || existingBlocks.length !== freshBlocks.length) return null;
	for (let i = 0; i < existingBlocks.length; i++) {
		if (existingBlocks[i]!.id !== freshBlocks[i]!.id) return null;
	}

	return {
		frontmatterPrefix: freshFm ? freshLines.slice(0, freshBodyStart) : [],
		existingFrontmatter: existingFm ? existingLines.slice(0, existingBodyStart) : [],
		existingBody,
		freshBody,
		existingBlocks,
		freshBlocks,
	};
}

/** One block of a note that an update would rewrite. */
export interface NoteChange {
	/** The marker id whose content changes, or null for the YAML frontmatter
	 *  block — that one is machine-generated and replaced as a whole, so it
	 *  has no marker of its own. */
	id: string | null;
	/** The block as it stands in the file and as the update would leave it,
	 *  marker lines stripped — what a preview shows the user. */
	before: string;
	after: string;
}

/**
 * What mergeNoteContent() would change about `existing`, block by block,
 * without changing anything: the marker regions whose content differs, plus
 * the frontmatter when that differs. An empty array means the merge would
 * leave the file byte-for-byte as it is; `null` means the merge would refuse
 * (see module doc) and the note would be left alone entirely.
 */
export function diffNoteContent(existing: string, fresh: string): NoteChange[] | null {
	const aligned = alignNotes(existing, fresh);
	if (!aligned) return null;

	const changes: NoteChange[] = [];
	const existingFm = aligned.existingFrontmatter.join('\n');
	const freshFm = aligned.frontmatterPrefix.join('\n');
	if (existingFm !== freshFm) changes.push({ id: null, before: existingFm, after: freshFm });

	for (let i = 0; i < aligned.existingBlocks.length; i++) {
		const eb = aligned.existingBlocks[i]!;
		const fb = aligned.freshBlocks[i]!;
		// A kept block is not rewritten, so the preview must not announce it.
		if (eb.kept) continue;
		// The marker lines themselves are skipped: they are invisible in the
		// note, and a legacy %%jw:…%% pair being upgraded to a span is not a
		// change the user has any reason to be shown.
		const before = aligned.existingBody.slice(eb.startLine + 1, eb.endLine).join('\n');
		const after = aligned.freshBody.slice(fb.startLine + 1, fb.endLine).join('\n');
		if (before !== after) changes.push({ id: eb.id, before, after });
	}
	return changes;
}

export function mergeNoteContent(existing: string, fresh: string): string | null {
	const aligned = alignNotes(existing, fresh);
	if (!aligned) return null;
	const { frontmatterPrefix, existingBody, freshBody, existingBlocks, freshBlocks } = aligned;

	const mergedBody = existingBody.slice();
	// Splice from the end backwards so earlier (not-yet-processed) indices stay valid.
	for (let i = existingBlocks.length - 1; i >= 0; i--) {
		const eb = existingBlocks[i]!;
		const fb = freshBlocks[i]!;
		// The user corrected this block on purpose (see markBlockKept): an
		// update must not undo that, or the correction would quietly come back
		// wrong on the next parser fix.
		if (eb.kept) continue;
		const freshSpan = freshBody.slice(fb.startLine, fb.endLine + 1);
		mergedBody.splice(eb.startLine, eb.endLine - eb.startLine + 1, ...freshSpan);
	}

	return [...frontmatterPrefix, ...mergedBody].join('\n');
}
